### ISSUE TITLE
Non-emote clue items

### ISSUE THREAD

**Issue by Popedigoz** [larsvansoest/emote-clue-items#100]
I know the plugin name itself says EMOTE Clue Items, but I had hi alched my D Scim because I thought there is 0% chance I'm going to need it (after receiving the whip). There is an Elite clue skill challenge to equip Dragon Scimitar. I rememer there being other like this too but they were easy and/or easily obtainable, now 100k for D scim that's it

**Comment by larsvansoest** [comment]
This plugin uses a copy of the data provided by the wiki:
https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Emote_clues/Items

The dragon scimitar is not listed there.

**Comment by Popedigoz** [comment]
did you even read
