### ISSUE TITLE
Plugin incompatable with the latest runelite update

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [larsvansoest/emote-clue-items#102]
![image](https://github.com/larsvansoest/emote-clue-items/assets/37377657/baaf7959-8b62-449e-9271-b09632532dad)

The flatlaf update to runelites UI has made this plugin incompatable and non-functional

**Comment by larsvansoest** [comment]
Thanks for your report. It seems you are trying to install version 4.2.1 of this plugin, while 4.2.2. adresses these issues. Are you sure your plugin hub is up to date?

**Comment by Jin-Jiyunsun** [comment]
Huh, its actually working today. Not sure why it didnt update before. :shrug:
