### ISSUE TITLE
Issue: Plugin needs updated for the latest version of Runelite

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [larsvansoest/emote-clue-items#105]
![oZoKnAYpNv](https://github.com/larsvansoest/emote-clue-items/assets/37377657/dbc41c96-86c2-42fe-9eaa-ed9aea48d080)
 Not much else to say, plugin needs updated to be compatable with the latest version of Runelite.

**Comment by larsvansoest** [comment]
Thank you for reporting this issue! 🚀

A patch has been implemented and is currently under review by RuneLite. 
You can track the current status here: https://github.com/runelite/plugin-hub/pull/5916
