### ISSUE TITLE
Sunfire Fanatic step no longer requires full set

### ISSUE THREAD

**Issue by joemckie** [larsvansoest/emote-clue-items#109]
This step was changed back in April (https://secure.runescape.com/m=news/varlamore-tweaks--drop-rates?oldschool=1), but the plugin still shows that the whole set is required.

![image](https://github.com/user-attachments/assets/0b0c092d-1484-4613-8856-7249df18b395)

**Comment by larsvansoest** [comment]
Thank you for reporting this issue! 🚀

A patch has been implemented and is currently under review by RuneLite.
You can track the current status here: https://github.com/runelite/plugin-hub/pull/6939
