### ISSUE TITLE
Plugin needs updated for the latest version of Runelite

### ISSUE THREAD

**Issue by liniim** [larsvansoest/emote-clue-items#112]
![image](https://github.com/user-attachments/assets/1acc7649-3459-4d8a-8b71-a33590741fa5)

Current version is 4.3.1, needs to be updated.

**Comment by larsvansoest** [comment]
Thank you for reporting this issue!

**Comment by larsvansoest** [comment]
A patch has been implemented and is currently under review by RuneLite.
You can track the current status here: https://github.com/runelite/plugin-hub/pull/6939
