### ISSUE TITLE
UIM can't get the progression to begin tracking

### ISSUE THREAD

**Issue by DenchyRS** [larsvansoest/emote-clue-items#19]
Title, can't begin progression because of my account type, would still be very useful for UIM too :D

**Comment by larsvansoest** [comment]
Thank you very much for reporting this issue. I will make to fix this in the next update soon!

**Comment by larsvansoest** [comment]
This feature is released through https://github.com/larsvansoest/emote-clue-items/releases/tag/v3.1.0 and currently live on RuneLite.
