### ISSUE TITLE
Missing item medium

### ISSUE THREAD

**Issue by tbjgolden** [larsvansoest/emote-clue-items#25]
Bush

Outside the Seers' Village courthouse

Adamant halberd • Mystic robe bottom • Diamond ring

**Comment by larsvansoest** [comment]
![image](https://user-images.githubusercontent.com/5564172/135507229-acf8091f-9242-4a3e-baeb-88dc70fc5446.png)

Hello, what missing item are you refering to? As illustrated by the screenshot, it seems like the STASHUnit you mentioned, with its contents, are supported by the plugin.

**Comment by larsvansoest** [comment]
Items seems not to be missing. If you have an update on your report, feel free to open a new issue!
