### ISSUE TITLE
Filled STASHes not saving - maybe add "check all" option?

### ISSUE THREAD

**Issue by kjholt** [larsvansoest/emote-clue-items#33]
I'm not sure if it's an issue on my end, but when I log in to RuneLite my built stashes are all marked as built but unfilled. A couple times I have gone through and checked them all off as filled, but it would be much easier with an option to mark all built stashes as filled.

The issue could be related to my having two different OSRS accounts with different RuneLite accounts/folders? It's possible I didn't set that up correctly but I followed the directions indicated by RuneLite.

Either way, this is one of my favorite plugins! Thank you so much!

**Comment by larsvansoest** [comment]
@TomBoj thank you for letting me know. How often are you experiencing this issue?

**Comment by larsvansoest** [comment]
### Bug Investigation
**Status**: reproduced
**Description**: logged into a runelite account, logged into a runescape account, set all stashes as filled. On logout, an exception occured. After rebooting runelite, all fill statuses disappeared.

**Comment by TomBoj** [comment]
It seems to happen every time I close and relaunch RuneLite, I've just done it now.
I have 3/3 beginner, 27/29 easy and 2/23 medium STASHs built and filled. I've attached a screenshot to show what the easy Stashes tab looks like when I login
![image](https://user-images.githubusercontent.com/7304411/144220339-7f4c6087-8d6c-43e2-95fd-26757483b724.png)

**Comment by larsvansoest** [comment]
Thanks for letting me know! I have been able to reproduce the bug, I will start debugging and propose a fix. Thanks for actively reporting this issue, really helps improving the project!

**Comment by TomBoj** [comment]
No problem, thanks for such a great plugin

**Comment by larsvansoest** [comment]
@kjholt @TomBoj Thank you for reporting this issue. It should be resolved once [plugin-hub:pr#2143](https://github.com/runelite/plugin-hub/pull/2143) is accepted for release.

**Comment by larsvansoest** [comment]
The changes were merged today. With release https://github.com/larsvansoest/emote-clue-items/releases/tag/v3.3.0 the fix should now be live on RuneLite!
