### ISSUE TITLE
Minor Issue: Spelling Error on Stash Unit 

### ISSUE THREAD

**Issue by maffdog** [larsvansoest/emote-clue-items#53]
the Stash unit Ardougne Zoo Parrots is incorrectly spelled as Aroudgne Zoo Parrots

(sorry if this is not normally how issues are reported, made an account on github to report this after accidentally coming across this)

![image](https://user-images.githubusercontent.com/104131100/164411606-90a36785-6e24-4fea-aa24-01d31be99954.png)

**Comment by larsvansoest** [comment]
Thank you for reporting this issue. This will be fixed in the next update!
