### ISSUE TITLE
Plugin missing from plugin hub

### ISSUE THREAD

**Issue by pystic-mizza** [larsvansoest/emote-clue-items#68]
Hey, I had this plugin installed but it suddenly disappeared from my installed plugin list. I cannot find it on the plugin hub either. Has it been removed? 

Thanks

**Comment by larsvansoest** [comment]
Thanks for reporting this issue. I will get in touch with the RuneLite devs!

**Comment by larsvansoest** [comment]
Apparently, RuneLite's new version causes the issue. I should patch the plugin to match with the new Pharao's scepter updates.

**Comment by larsvansoest** [comment]
A hotfix has been submitted for review to the RuneLite devs. Once resolved, the plugin should be up and running again.

@pystic-mizza Thanks a lot for reporting this issue! Apologies for the inconvenience.

For more info, see: https://github.com/runelite/plugin-hub/pull/2623.
