### ISSUE TITLE
ISSUE: Plugin broken after latest RL update

### ISSUE THREAD

**Issue by eX-C0n** [larsvansoest/emote-clue-items#70]
Title self explanitory, the latest update broke Emote Clue Items

RuneLite
BOT
 — Today at 12:16 PM
Some hub plugins failed to build against the latest RuneLite version, this means that they're not available until the owner updates them.

**Comment by larsvansoest** [comment]
Thank you for reporting this issue! I will start investigating

**Comment by larsvansoest** [comment]
Currently, a hotfix is under review. You can follow the status at https://github.com/runelite/plugin-hub/pull/3007
