### ISSUE TITLE
Item still says I need it

### ISSUE THREAD

**Issue by forfiet2** [larsvansoest/emote-clue-items#72]
i filled the stash unit that needed rune platelegs and when I go to my bank it says I still need it for stashes. 

![RuneLite_BIpgog0M1w](https://user-images.githubusercontent.com/34373905/189552183-fefb6622-ab58-44dd-8d69-d862036c5c73.png)
![RuneLite_i0UhmujETY](https://user-images.githubusercontent.com/34373905/189552194-010d3700-ae7e-4781-91e2-794f961f42ed.png)

@larsvansoest

**Comment by ChaoticElements** [comment]
There's two stash units that require rune platelegs. take a look and see if you've done both the Wilderness Chaos Temple stash and the Jiggig stash.
![image](https://user-images.githubusercontent.com/20726466/192229497-458355cc-3c3d-44e1-99ff-096a9c51b2dd.png)
![image](https://user-images.githubusercontent.com/20726466/192229535-a204a864-ed7a-4b02-88b3-5c375eff3647.png)

**Comment by larsvansoest** [comment]
@ChaoticElements, thanks for handling this story!

@forfiet2 If you experience the same result with checking both stash units, feel free to reopen this issue!

**Comment by forfiet2** [comment]
Why doesn't the plugin automatically check off the stashes when done? I had to manually click one as filled. [https://i.imgur.com/4t14w1S.png](url) I checked it to make sure.
