### ISSUE TITLE
The plugin was removed from the Runelite hub and the client

### ISSUE THREAD

**Issue by HollowGrey** [larsvansoest/emote-clue-items#78]
Title - the plugin was removed from runelite. Cannot find it in the plugin hub anymore.

**Comment by infusion1** [comment]
Same issue here, can't find it anywhere within runelite.

**Comment by larsvansoest** [comment]
Thank you for reporting this issue. A path to fix this issue is currently under review by RuneLite. For the review status, please see https://github.com/runelite/plugin-hub/pull/3616

**Comment by larsvansoest** [comment]
Duplicates #76

**Comment by HollowGrey** [comment]
Hey Lars, thanks for jumping on this so quickly. I really appreciate the plugin you have created and MAINTAIN. You are awesome!

**Comment by larsvansoest** [comment]
You're welcome! Thanks for supporting the project!
