### ISSUE TITLE
Filter By Clue Type

### ISSUE THREAD

**Issue by TzKal-Zuk** [larsvansoest/emote-clue-items#79]
Would it be possible to add a filter for different types of clue scrolls?

I already have all the easy and medium STASH units filled, so I really don't need the indicator for those items anymore. It would be great if I could turn the indicator off for easy and medium items, but keep indicators on for Hard, Elite, and Master items.

**Comment by larsvansoest** [comment]
Thanks for your suggestion!

It should be already possible to filter the corresponding items as follows:

- In the plugin settings, make sure that items in stashes are not highlighted.
- In the plugin stash unit panel, filter by easy, and set all stashes to filled by clicking the white squares next to the stash names.
- Then, filter by medium, and again set all to filled.

Does following the steps above achieve what you are looking for?
