### ISSUE TITLE
Filter Items in STASH not working

### ISSUE THREAD

**Issue by Rough-Draft** [larsvansoest/emote-clue-items#80]
I have completed all my beginner and easy STASHes. I triple checked and items like white apron and iron pickaxe are definitely in my STASHes but it  still shows the little easy clue dot next to them.

**Comment by larsvansoest** [comment]
@Rough-Draft thanks for opening an issue. Would you mind following the checklist below?

1. As shown in the screenshot below, the white apron is used in two different stashes, did you fill them both?
   ![image](https://user-images.githubusercontent.com/5564172/213421369-7e4f9ca3-9e10-4d16-a2a8-75338694786e.png)
2. Did you select "filled" for all stash units by clicking on the white box?
   ![image](https://user-images.githubusercontent.com/5564172/213421608-16792d6e-7310-4c8d-aaff-eb39cae32bb9.png)
   ![image](https://user-images.githubusercontent.com/5564172/213421659-89de46f1-8499-4d05-b9d9-1aaf1c727b4b.png)
3. Did you enable "Filter items in stash" in the plugin settings?
   ![image](https://user-images.githubusercontent.com/5564172/213421827-b97df1cd-d261-406f-ae7a-56b1e16df5b6.png)

For now, I am closing this issue. If you observe the same behaviour after following these steps, please let me know!
