### ISSUE TITLE
Varrock Palace Library is misspelled 

### ISSUE THREAD

**Issue by CMDMC12** [larsvansoest/emote-clue-items#86]
![image](https://user-images.githubusercontent.com/27746140/216751158-5cf1e6fa-9235-4ecb-8db2-c45b63c37d3e.png)

**Comment by larsvansoest** [comment]
Thanks for reporting this issue! The plugin changes are now up for review at https://github.com/runelite/plugin-hub/pull/3938. It will be fixed as soon as they are accepted by RuneLite.
