### ISSUE TITLE
latest update broke interface highlighting

### ISSUE THREAD

**Issue by scorchedmuffins** [larsvansoest/emote-clue-items#89]
No longer get colored dots on items in bank or inventory after today's update.

**Comment by scorchedmuffins** [comment]
![RuneLite_2023-02-20_09-46-45](https://user-images.githubusercontent.com/125899694/220172663-2b09b0b8-827e-445f-918f-1db03c6a8f6d.png)
here is a screenshot of settings and a rune halberd in inventory without a dot on it

**Comment by larsvansoest** [comment]
I was able to reproduce this issue and will start working on a fix, thanks a lot for reporting it!

**Comment by larsvansoest** [comment]
The issue was found and patched. The plugin changes are now up for review at https://github.com/runelite/plugin-hub/pull/3938. It will be fixed as soon as they are accepted by RuneLite.

**Comment by larsvansoest** [comment]
The changes were just accepted by RuneLite, thanks again for reporting!
