### ISSUE TITLE
Medium Clue Step Addy armor not logging

### ISSUE THREAD

**Issue by loegare** [larsvansoest/emote-clue-items#91]
When I put my addy armor into the stash for the medium clue step it gets marked in the plugin as missing

**Comment by larsvansoest** [comment]
@loegare hey there, did you also set the stash unit as filled in the plugin panel? You can do so by clicking the white square next to the stash unit in the stash unit overview.

**Comment by loegare** [comment]
after clicking that square it is no longer marked as missing
