### ISSUE TITLE
Warrior Guild Elite STASH Bug

### ISSUE THREAD

**Issue by purush97** [larsvansoest/emote-clue-items#93]
the warrior guild elite clue STASH unit (black salamander) does not properly sync when using the "sync Watson board" setting.
It repeatedly marks itself as empty despite being filled. 

https://i.imgur.com/v7h9MW5.gif

**Comment by larsvansoest** [comment]
Thanks for reporting this issue.

It should be fixed in the next patch. The patch is currently under review.

Please consider the following link to view its status:
https://github.com/runelite/plugin-hub/pull/4466
